import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen bg-gradient-to-b from-red-100 to-blue-300">{children}</body>
    </html>
  )
}
